protocgen, readme: add additional setup instructions
cosmos/groups-ui pull request #25
Opened 2022-02-18 03:55 UTC by matildepark

Just writing down some documentation for stuff I was getting stuck on while setting this up on my M1 Mac. Some of this (like that `$GOPATH` is there at all) is expected for developers to have [based on the Tendermint docs](https://docs.tendermint.com/master/app-dev/getting-started.html#install), but instructions for a full-stack product like this are best made thorough and explicit, I think.

Secondly, the protocgen script assumes the user's environment, so this adds some conditional checks so Mac users can build without hassle.

Let me know if any of this is off base...

2022-03-13 11:37 UTC, vlamitin commented
Thanks for pointing this out!
This is in a very deep develpment now, and currently used latest cosmos-sdk node is now yet works correctly with this front-end. And that's why only development in linux was supported.

2022-03-13 11:41 UTC, vlamitin requested changes

2022-03-13 11:41 UTC, vlamitin commented on README.md
> +- `tendermint`
no tendermint install is needed, just go to build cosmos-sdk simd

2022-03-13 11:41 UTC, vlamitin commented on README.md
> +Ensure you have a Tendermint node running locally and that CORS is allowed from any origin in `config.toml`.
In latest cosmos-sdk cors directives in config.toml is ignored (we are communicating with cosmos-sdk development team on it), so workaround for development for now is some chrome extension to bypass this, like this one https://chrome.google.com/webstore/detail/digfbfaphojjndkpccljibejjbppifbc (you can point it here in README)

2022-04-21 17:51 UTC, matildepark commented
Closing because mostly remedied by new README.

2022-04-21 17:51 UTC, closed without merging